### ISSUE TITLE
vim output on exit

### ISSUE THREAD

**Issue by Pectojin** [nightsense/office#1]
Enabling office-dark or office-light causes vim to output `\e]12;#949488` in my terminal after i exit vim.
![image](https://user-images.githubusercontent.com/1561484/31585868-46c565d4-b1c9-11e7-986e-f2fecf6c0be0.png)

I can't quite figure out what's causing it in the config file, but the output goes away as soon as i change color scheme to any of the default ones.

**Comment by nightsense** [comment]
Hi Pectojin, what terminal application are you using? That output is from the command that sets the terminal cursor colour (it's the last line of each `~/.nightshell/THEME` script), so I'll try wrapping the command in a conditional statement of some sort.

**Comment by Pectojin** [comment]
Hi Nightsense,

It happens on both Gnome Terminal 3.20.2 and Tilix 1.6.4 on my Ubuntu 17.04 installation.
I tried outcommenting the lines with the "949488" color, but I must have broken the syntax because that just gave me errors.

**Comment by nightsense** [comment]
OK, I've removed the line I think is causing the issue, so that problem should be fixed. Let me know if not.

**Comment by Pectojin** [comment]
I'm afraid I still get same output on exit after running PlugUpdate. I checked the git repo in ~/.vim/plugged/office and it says it's up to date as well.

I'm starting to think it might be some factor outside the terminal application itself. I've had same results in Gnome-terminal, Tilix, XFCE terminal, Terminology, Termit, and Konsole.

**Comment by nightsense** [comment]
I think the issue is with nightshell, try bringing it up to date (cd to ~/.nightshell and run `git pull`).

**Comment by Pectojin** [comment]
Oh, awesome. That fixed it right away. On all the terminal applications.

Thanks for the assistance on this. I really love the office-dark theme.

The only slight disappointment is that Mosh acts poorly with it because it doesn't support true color, while SSH works perfectly.

**Comment by nightsense** [comment]
No problem, glad you like it :frog:
